/**
 * @file planetkit_cc_param.h
 * @brief write some brief information here.
 *
 * @date 2022-11-10
 *
 * Generated by genc_planetkit.py v1.0
 *
 */

#ifndef __PLANETKIT_CC_PARAM_H__
#define __PLANETKIT_CC_PARAM_H__


/*************************************************************************
* INCLUDE
*************************************************************************/
#include "planetkit_common_type.h"


#if defined(__cplusplus)
extern "C" {
#endif
/*************************************************************************
* DATA STRUCTURE
*************************************************************************/

typedef struct planetkit_cc_param_t planetkit_cc_param_t;

/*************************************************************************
* API DEFINITION
*************************************************************************/

planetkit_cc_param_t *NULLABLE  planetkit_cc_param_create(planetkit_str_t NONNULL b64_call_param);
void                            planetkit_cc_param_release(planetkit_cc_param_t * NONNULL cc_param);

planetkit_str_t NULLABLE        planetkit_cc_param_get_peer_id(planetkit_cc_param_t *NONNULL cc_param);
planetkit_str_t NULLABLE        planetkit_cc_param_get_peer_service_id(planetkit_cc_param_t *NONNULL cc_param);
planetkit_media_type_e          planetkit_cc_param_get_media_type(planetkit_cc_param_t *NONNULL cc_param);

#if defined(__cplusplus)
}
#endif

#endif /* __PLANETKIT_CC_PARAM_H__ */

