/**
 * @file planetkit_send_voice_processor.h
 * @brief write some brief information here.
 *
 * @date 2022-08-23
 *
 * Generated by genc_planetkit.py v1.0
 *
 */

#ifndef __PLANETKIT_VOICE_PROCESSOR_H__
#define __PLANETKIT_VOICE_PROCESSOR_H__


/*************************************************************************
* INCLUDE
*************************************************************************/
#include "planetkit_common_type.h"


#if defined(__cplusplus)
extern "C" {
#endif
/*************************************************************************
* DATA STRUCTURE
*************************************************************************/

typedef struct planetkit_send_voice_processor planetkit_send_voice_processor_t;

/*************************************************************************
* API DEFINITION
*************************************************************************/
kit_bool_t  planetkit_send_voice_processor_enable(planetkit_send_voice_processor_t * NONNULL processor, void * NULLABLE user_ptr, planetkit_result_handler_t NULLABLE result_handler);
kit_bool_t  planetkit_send_voice_processor_disable(planetkit_send_voice_processor_t * NONNULL processor, void * NULLABLE user_ptr, planetkit_result_handler_t NULLABLE result_handler);
kit_bool_t  planetkit_send_voice_processor_get_enabled(planetkit_send_voice_processor_t * NONNULL processor);

kit_bool_t  planetkit_send_voice_processor_set_acoustic_echo_canceller_mode(planetkit_send_voice_processor_t * NONNULL processor, planetkit_acoustic_echo_canceller_mode_e mode,
                                                                            void * NULLABLE result_handler_user, planetkit_result_handler_t NULLABLE result_handler);
planetkit_acoustic_echo_canceller_mode_e planetkit_send_voice_processor_get_acoustic_canceller_mode(planetkit_send_voice_processor_t * NONNULL processor);

kit_bool_t  planetkit_send_voice_processor_set_noise_suppressor_mode(planetkit_send_voice_processor_t * NONNULL processor, planetkit_noise_suppressor_mode_e mode,
                                                                     void * NULLABLE user_ptr, planetkit_result_handler_t NULLABLE result_handler);
planetkit_noise_suppressor_mode_e planetkit_send_voice_processor_get_noise_suppressor_mode(planetkit_send_voice_processor_t * NONNULL processor);

kit_bool_t  planetkit_send_voice_processor_set_auto_gain_control(planetkit_send_voice_processor_t * NONNULL processor, planetkit_auto_gain_control_param_t * NONNULL param,
                                                                 void * NULLABLE user_ptr, planetkit_result_handler_t NULLABLE result_handler);
planetkit_auto_gain_control_mode_e planetkit_send_voice_processor_get_auto_gain_control_mode(planetkit_send_voice_processor_t * NONNULL processor);
kit_bool_t  planetkit_send_voice_processor_interactive_auto_gain_control_inform_hw_level(planetkit_send_voice_processor_t * NONNULL processor, planetkit_audio_hw_type_e hw_type, float hw_level,
                                                                                         void * NULLABLE user_ptr, planetkit_result_handler_t NULLABLE result_handler);


#if defined(__cplusplus)
}
#endif

#endif /* __PLANETKIT_VOICE_PROCESSOR_H__ */

