/**
 * @file planetkit_call_start_message.h
 * @brief write some brief information here.
 *
 * @date 2023-04-06
 *
 * Generated by genc_planetkit.py v1.0
 *
 */

#ifndef __PLANETKIT_CALL_START_MESSAGE_H__
#define __PLANETKIT_CALL_START_MESSAGE_H__

/*************************************************************************
* INCLUDE
*************************************************************************/
#include "planetkit_common_type.h"

#if defined(__cplusplus)
extern "C" {
#endif

/*************************************************************************
* DATA STRUCTURE
*************************************************************************/

typedef struct planetkit_call_start_message_t planetkit_call_start_message_t;

/*************************************************************************
* API DEFINITION
*************************************************************************/

/**
 * @param data Maximum size of data is 200 bytes including null termination
 */
planetkit_call_start_message_t * NULLABLE   planetkit_call_start_message_create(planetkit_str_t NONNULL data);
kit_bool_t                              planetkit_call_start_message_retain(planetkit_call_start_message_t *NONNULL call_start_message);
void                                    planetkit_call_start_message_release(planetkit_call_start_message_t *NONNULL call_start_message);

planetkit_str_t              NULLABLE   planetkit_call_start_message_get(planetkit_call_start_message_t *NULLABLE call_start_message);

kit_bool_t                              planetkit_call_start_message_is_available(planetkit_str_t NONNULL data);

#if defined(__cplusplus)
}
#endif

#endif /* __PLANETKIT_CALL_START_MESSAGE_H__ */

