// Mocks generated by Mockito 5.4.6 from annotations
// in planet_kit_flutter/test/mocks/mock_platform.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i13;

import 'package:flutter/src/services/binary_messenger.dart' as _i3;
import 'package:flutter/src/services/message_codec.dart' as _i2;
import 'package:flutter/src/services/platform_channel.dart' as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:planet_kit_flutter/src/internal/call/planet_kit_platform_background_call_event.dart'
    as _i11;
import 'package:planet_kit_flutter/src/internal/call/planet_kit_platform_call_event.dart'
    as _i6;
import 'package:planet_kit_flutter/src/internal/camera/planet_kit_platform_camera_event.dart'
    as _i10;
import 'package:planet_kit_flutter/src/internal/conference/planet_kit_platform_conference_event.dart'
    as _i8;
import 'package:planet_kit_flutter/src/internal/my_media_status/planet_kit_platform_my_media_status_event.dart'
    as _i7;
import 'package:planet_kit_flutter/src/internal/peer_control/planet_kit_platform_peer_control_event.dart'
    as _i9;
import 'package:planet_kit_flutter/src/internal/planet_kit_platform_interface.dart'
    as _i4;
import 'package:planet_kit_flutter/src/public/planet_kit_types.dart' as _i12;
import 'package:planet_kit_flutter/src/public/planet_kit_user_id.dart' as _i15;
import 'package:planet_kit_flutter/src/public/statistics/planet_kit_statistics.dart'
    as _i14;
import 'package:planet_kit_flutter/src/public/video/planet_kit_video_resolution.dart'
    as _i17;
import 'package:planet_kit_flutter/src/public/video/planet_kit_video_status.dart'
    as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMethodCodec_0 extends _i1.SmartFake implements _i2.MethodCodec {
  _FakeMethodCodec_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBinaryMessenger_1 extends _i1.SmartFake
    implements _i3.BinaryMessenger {
  _FakeBinaryMessenger_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventManagerInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventManagerInterface extends _i1.Mock
    implements _i4.EventManagerInterface {
  MockEventManagerInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.CallEvent> get onCallEvent => (super.noSuchMethod(
        Invocation.getter(#onCallEvent),
        returnValue: _i5.Stream<_i6.CallEvent>.empty(),
      ) as _i5.Stream<_i6.CallEvent>);

  @override
  _i5.Stream<_i7.MyMediaStatusEvent> get onMyMediaStatusEvent =>
      (super.noSuchMethod(
        Invocation.getter(#onMyMediaStatusEvent),
        returnValue: _i5.Stream<_i7.MyMediaStatusEvent>.empty(),
      ) as _i5.Stream<_i7.MyMediaStatusEvent>);

  @override
  _i5.Stream<_i8.ConferenceEvent> get onConferenceEvent => (super.noSuchMethod(
        Invocation.getter(#onConferenceEvent),
        returnValue: _i5.Stream<_i8.ConferenceEvent>.empty(),
      ) as _i5.Stream<_i8.ConferenceEvent>);

  @override
  _i5.Stream<_i9.PeerControlEvent> get onPeerControlEvent =>
      (super.noSuchMethod(
        Invocation.getter(#onPeerControlEvent),
        returnValue: _i5.Stream<_i9.PeerControlEvent>.empty(),
      ) as _i5.Stream<_i9.PeerControlEvent>);

  @override
  _i5.Stream<_i10.CameraEvent> get onCameraEvent => (super.noSuchMethod(
        Invocation.getter(#onCameraEvent),
        returnValue: _i5.Stream<_i10.CameraEvent>.empty(),
      ) as _i5.Stream<_i10.CameraEvent>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addHookedAudioHandler(
    String? id,
    _i4.HookedAudioHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addHookedAudioHandler,
          [
            id,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeHookedAudioHandler(String? id) => super.noSuchMethod(
        Invocation.method(
          #removeHookedAudioHandler,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BackgroundEventManagerInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackgroundEventManagerInterface extends _i1.Mock
    implements _i4.BackgroundEventManagerInterface {
  MockBackgroundEventManagerInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i11.BackgroundCallEvent> get onCallEvent => (super.noSuchMethod(
        Invocation.getter(#onCallEvent),
        returnValue: _i5.Stream<_i11.BackgroundCallEvent>.empty(),
      ) as _i5.Stream<_i11.BackgroundCallEvent>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CallInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallInterface extends _i1.Mock implements _i4.CallInterface {
  MockCallInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> acceptCall(
    String? callId,
    bool? useResponderPreparation,
    _i12.PlanetKitInitialMyVideoState? initialMyVideoState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptCall,
          [
            callId,
            useResponderPreparation,
            initialMyVideoState,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> endCall(
    String? callId,
    String? userReleasePhrase,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #endCall,
          [
            callId,
            userReleasePhrase,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> endCallWithError(
    String? callId,
    String? userReleasePhrase,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #endCallWithError,
          [
            callId,
            userReleasePhrase,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> muteMyAudio(
    String? callId,
    bool? mute,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteMyAudio,
          [
            callId,
            mute,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> speakerOut(
    String? callId,
    bool? speakerOut,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #speakerOut,
          [
            callId,
            speakerOut,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isSpeakerOut(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #isSpeakerOut,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isMyAudioMuted(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #isMyAudioMuted,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isPeerAudioMuted(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #isPeerAudioMuted,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> enableHookMyAudio(
    String? callId,
    _i4.HookedAudioHandler? handler,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableHookMyAudio,
          [
            callId,
            handler,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> disableHookMyAudio(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #disableHookMyAudio,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> putHookedMyAudioBack(
    String? callId,
    String? audioId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putHookedMyAudioBack,
          [
            callId,
            audioId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setHookedAudioData(
    String? audioId,
    _i13.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHookedAudioData,
          [
            audioId,
            data,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isHookMyAudioEnabled(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #isHookMyAudioEnabled,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> notifyCallKitAudioActivation(String? callId) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyCallKitAudioActivation,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> finishPreparation(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #finishPreparation,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isOnHold(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #isOnHold,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> hold(
    String? callId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hold,
          [
            callId,
            reason,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> unhold(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #unhold,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestPeerMute(
    String? callId,
    bool? mute,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPeerMute,
          [
            callId,
            mute,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String?> getMyMediaStatus(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #getMyMediaStatus,
          [callId],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> silencePeerAudio(
    String? callId,
    bool? silent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #silencePeerAudio,
          [
            callId,
            silent,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> addMyVideoView(
    String? callId,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMyVideoView,
          [
            callId,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeMyVideoView(
    String? callId,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMyVideoView,
          [
            callId,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> addPeerVideoView(
    String? callId,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPeerVideoView,
          [
            callId,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> removePeerVideoView(
    String? callId,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePeerVideoView,
          [
            callId,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> pauseMyVideo(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #pauseMyVideo,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> resumeMyVideo(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #resumeMyVideo,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> enableVideo(
    String? callId,
    _i12.PlanetKitInitialMyVideoState? initialMyVideoState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableVideo,
          [
            callId,
            initialMyVideoState,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> disableVideo(
    String? callId,
    _i12.PlanetKitMediaDisableReason? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #disableVideo,
          [
            callId,
            reason,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i14.PlanetKitStatistics?> getStatistics(String? callId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [callId],
        ),
        returnValue: _i5.Future<_i14.PlanetKitStatistics?>.value(),
      ) as _i5.Future<_i14.PlanetKitStatistics?>);

  @override
  _i5.Future<bool> addPeerScreenShareView(
    String? callId,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPeerScreenShareView,
          [
            callId,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> removePeerScreenShareView(
    String? callId,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePeerScreenShareView,
          [
            callId,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> startMyScreenShare(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #startMyScreenShare,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> stopMyScreenShare(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #stopMyScreenShare,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setSharedContents(
    String? callId,
    _i13.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSharedContents,
          [
            callId,
            data,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> unsetSharedContents(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #unsetSharedContents,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setExclusivelySharedContents(
    String? callId,
    _i13.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExclusivelySharedContents,
          [
            callId,
            data,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> unsetExclusivelySharedContents(String? callId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsetExclusivelySharedContents,
          [callId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> sendShortData(
    String? callId,
    String? type,
    _i13.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendShortData,
          [
            callId,
            type,
            data,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> makeOutboundDataSession(
    String? callId,
    int? streamId,
    int? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeOutboundDataSession,
          [
            callId,
            streamId,
            type,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> makeInboundDataSession(
    String? callId,
    int? streamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeInboundDataSession,
          [
            callId,
            streamId,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> unsupportInboundDataSession(
    String? callId,
    int? streamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsupportInboundDataSession,
          [
            callId,
            streamId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int?> getOutboundDataSessionType(
    String? callId,
    int? streamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutboundDataSessionType,
          [
            callId,
            streamId,
          ],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<int?> getInboundDataSessionType(
    String? callId,
    int? streamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInboundDataSessionType,
          [
            callId,
            streamId,
          ],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<bool> dataSessionSend(
    String? callId,
    int? streamId,
    _i13.Uint8List? data,
    int? timestamp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #dataSessionSend,
          [
            callId,
            streamId,
            data,
            timestamp,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [ConferenceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockConferenceInterface extends _i1.Mock
    implements _i4.ConferenceInterface {
  MockConferenceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> leaveConference(String? id) => (super.noSuchMethod(
        Invocation.method(
          #leaveConference,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> muteMyAudio(
    String? id,
    bool? mute,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteMyAudio,
          [
            id,
            mute,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> speakerOut(
    String? id,
    bool? speakerOut,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #speakerOut,
          [
            id,
            speakerOut,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isSpeakerOut(String? id) => (super.noSuchMethod(
        Invocation.method(
          #isSpeakerOut,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> notifyCallKitAudioActivation(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyCallKitAudioActivation,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> silencePeersAudio(
    String? id,
    bool? silent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #silencePeersAudio,
          [
            id,
            silent,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestPeerMute(
    String? id,
    bool? mute,
    _i15.PlanetKitUserId? peerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPeerMute,
          [
            id,
            mute,
            peerId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestPeersMute(
    String? id,
    bool? mute,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPeersMute,
          [
            id,
            mute,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isOnHold(String? id) => (super.noSuchMethod(
        Invocation.method(
          #isOnHold,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> hold(
    String? id,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hold,
          [
            id,
            reason,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> unhold(String? id) => (super.noSuchMethod(
        Invocation.method(
          #unhold,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String?> getMyMediaStatus(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMyMediaStatus,
          [id],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> createPeerControl(
    String? conferenceId,
    String? peerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPeerControl,
          [
            conferenceId,
            peerId,
          ],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> addMyVideoView(
    String? conferenceId,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMyVideoView,
          [
            conferenceId,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeMyVideoView(
    String? conferenceId,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMyVideoView,
          [
            conferenceId,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> enableVideo(
    String? id,
    _i12.PlanetKitInitialMyVideoState? initialMyVideoState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableVideo,
          [
            id,
            initialMyVideoState,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> disableVideo(String? id) => (super.noSuchMethod(
        Invocation.method(
          #disableVideo,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> pauseMyVideo(String? id) => (super.noSuchMethod(
        Invocation.method(
          #pauseMyVideo,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> resumeMyVideo(String? id) => (super.noSuchMethod(
        Invocation.method(
          #resumeMyVideo,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i14.PlanetKitStatistics?> getStatistics(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [id],
        ),
        returnValue: _i5.Future<_i14.PlanetKitStatistics?>.value(),
      ) as _i5.Future<_i14.PlanetKitStatistics?>);

  @override
  _i5.Future<bool> startMyScreenShare(String? conferenceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #startMyScreenShare,
          [conferenceId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> stopMyScreenShare(String? conferenceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopMyScreenShare,
          [conferenceId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setSharedContents(
    String? id,
    _i13.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSharedContents,
          [
            id,
            data,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> unsetSharedContents(String? id) => (super.noSuchMethod(
        Invocation.method(
          #unsetSharedContents,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setExclusivelySharedContents(
    String? id,
    _i13.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExclusivelySharedContents,
          [
            id,
            data,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> unsetExclusivelySharedContents(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsetExclusivelySharedContents,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setRoomSharedContents(
    String? id,
    _i13.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRoomSharedContents,
          [
            id,
            data,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> unsetRoomSharedContents(String? id) => (super.noSuchMethod(
        Invocation.method(
          #unsetRoomSharedContents,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> sendShortData(
    String? id,
    String? type,
    _i13.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendShortData,
          [
            id,
            type,
            data,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> sendShortDataToPeer(
    String? id,
    _i15.PlanetKitUserId? peerId,
    String? type,
    _i13.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendShortDataToPeer,
          [
            id,
            peerId,
            type,
            data,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> makeOutboundDataSession(
    String? id,
    int? streamId,
    int? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeOutboundDataSession,
          [
            id,
            streamId,
            type,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> makeInboundDataSession(
    String? id,
    int? streamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeInboundDataSession,
          [
            id,
            streamId,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> unsupportInboundDataSession(
    String? id,
    int? streamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsupportInboundDataSession,
          [
            id,
            streamId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int?> getOutboundDataSessionType(
    String? id,
    int? streamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutboundDataSessionType,
          [
            id,
            streamId,
          ],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<int?> getInboundDataSessionType(
    String? id,
    int? streamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInboundDataSessionType,
          [
            id,
            streamId,
          ],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<bool> dataSessionSend(
    String? id,
    int? streamId,
    _i13.Uint8List? data,
    int? timestamp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #dataSessionSend,
          [
            id,
            streamId,
            data,
            timestamp,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [MyMediaStatusInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyMediaStatusInterface extends _i1.Mock
    implements _i4.MyMediaStatusInterface {
  MockMyMediaStatusInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isMyAudioMuted(String? myMediaStatusId) =>
      (super.noSuchMethod(
        Invocation.method(
          #isMyAudioMuted,
          [myMediaStatusId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i16.PlanetKitVideoStatus?> getMyVideoStatus(
          String? myMediaStatusId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyVideoStatus,
          [myMediaStatusId],
        ),
        returnValue: _i5.Future<_i16.PlanetKitVideoStatus?>.value(),
      ) as _i5.Future<_i16.PlanetKitVideoStatus?>);
}

/// A class which mocks [PeerControlInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerControlInterface extends _i1.Mock
    implements _i4.PeerControlInterface {
  MockPeerControlInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> register(String? id) => (super.noSuchMethod(
        Invocation.method(
          #register,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> unregister(String? id) => (super.noSuchMethod(
        Invocation.method(
          #unregister,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> startVideo(
    String? id,
    String? viewId,
    _i17.PlanetKitVideoResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startVideo,
          [
            id,
            viewId,
            resolution,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> stopVideo(
    String? id,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopVideo,
          [
            id,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> startScreenShare(
    String? id,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startScreenShare,
          [
            id,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> stopScreenShare(
    String? id,
    String? viewId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopScreenShare,
          [
            id,
            viewId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [EventChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventChannel extends _i1.Mock implements _i18.EventChannel {
  MockEventChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i19.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i2.MethodCodec get codec => (super.noSuchMethod(
        Invocation.getter(#codec),
        returnValue: _FakeMethodCodec_0(
          this,
          Invocation.getter(#codec),
        ),
      ) as _i2.MethodCodec);

  @override
  _i3.BinaryMessenger get binaryMessenger => (super.noSuchMethod(
        Invocation.getter(#binaryMessenger),
        returnValue: _FakeBinaryMessenger_1(
          this,
          Invocation.getter(#binaryMessenger),
        ),
      ) as _i3.BinaryMessenger);

  @override
  _i5.Stream<dynamic> receiveBroadcastStream([dynamic arguments]) =>
      (super.noSuchMethod(
        Invocation.method(
          #receiveBroadcastStream,
          [arguments],
        ),
        returnValue: _i5.Stream<dynamic>.empty(),
      ) as _i5.Stream<dynamic>);
}
