/**
 * @file planetkit_my_status.h
 * @brief write some brief information here.
 *
 * @date 2023-03-21
 *
 * Generated by genc_planetkit.py v1.0
 *
 */

#ifndef __PLANETKIT_MY_STATUS_H__
#define __PLANETKIT_MY_STATUS_H__


/*************************************************************************
* INCLUDE
*************************************************************************/
#include "planetkit_common_type.h"

#if defined(__cplusplus)
extern "C" {
#endif
/*************************************************************************
* DATA STRUCTURE
*************************************************************************/

typedef struct planetkit_my_media_status_t planetkit_my_media_status_t;

typedef enum planetkit_my_media_status_updated_evt_e
{
    PLANETKIT_MY_MEDIA_STATUS_UPDATED_EVT_VIDEO_STATUS,         // video_status
    PLANETKIT_MY_MEDIA_STATUS_UPDATED_EVT_VIDEO_SUBGROUP,       // video_subgroup
    PLANETKIT_MY_MEDIA_STATUS_UPDATED_EVT_SCREEN_SHARE_STATE,   // screen_share_state
    PLANETKIT_MY_MEDIA_STATUS_UPDATED_EVT_SCREEN_SHARE_SUBGROUP,// screen_share_subgroup
    PLANETKIT_MY_MEDIA_STATUS_UPDATED_EVT_AUDIO_MUTED,          // no param
    PLANETKIT_MY_MEDIA_STATUS_UPDATED_EVT_AUDIO_UNMUTED,        // no param
    PLANETKIT_MY_MEDIA_STATUS_UPDATED_EVT_AUDIO_SUBGROUP,       // audio_subgroup
} planetkit_my_media_status_updated_evt_e;

typedef struct planetkit_my_media_status_updated_evt_param_t
{
    planetkit_my_media_status_updated_evt_e evt;

    union
    {
        struct {
            planetkit_video_status_t *NONNULL   status;
        } video_status;

        struct {
            planetkit_str_t NULLABLE            dst_subgrp_name;
        } video_subgroup;

        struct {
            planetkit_screen_share_state_e      state;
        } screen_share_state;

        struct {
            planetkit_str_t NULLABLE            dst_subgrp_name;
        } screen_share_subgroup;

        struct {
            planetkit_str_t NULLABLE            dst_subgrp_name;
            planetkit_str_t NULLABLE            tagged_subgrp_name;
        } audio_subgroup;
    };
} planetkit_my_media_status_updated_evt_param_t;

typedef void (*planetkit_my_media_status_updated_evt_handler_t)(planetkit_my_media_status_t *NONNULL my_media_status,
                                                                planetkit_my_media_status_updated_evt_param_t *NONNULL param,
                                                                void *NULLABLE user_ptr);

/*************************************************************************
* API DEFINITION
*************************************************************************/

kit_bool_t  planetkit_my_media_status_retain(planetkit_my_media_status_t *NONNULL my_media_status);
void        planetkit_my_media_status_release(planetkit_my_media_status_t *NONNULL my_media_status);

void        planetkit_my_media_status_get_video_subgroup_name(planetkit_my_media_status_t *NONNULL my_media_status, kit_bool_t *NONNULL out_is_subgrp, planetkit_subgrp_name_t *NONNULL out_subgrp_name);
void        planetkit_my_media_status_get_video_status(planetkit_my_media_status_t *NONNULL my_media_status, planetkit_video_status_t *NONNULL out_video_status);

void        planetkit_my_media_status_get_screen_share_subgroup_name(planetkit_my_media_status_t *NONNULL my_media_status, kit_bool_t *NONNULL out_is_subgrp, planetkit_subgrp_name_t *NONNULL out_subgrp_name);
planetkit_screen_share_state_e planetkit_my_media_status_get_screen_share_state(planetkit_my_media_status_t *NONNULL my_media_status);

void        planetkit_my_media_status_get_audio_subgroup_name(planetkit_my_media_status_t *NONNULL my_media_status, kit_bool_t *NONNULL out_is_subgrp, planetkit_subgrp_name_t *NONNULL out_subgrp_name);
void        planetkit_my_media_status_get_audio_tagged_subgroup_name(planetkit_my_media_status_t *NONNULL my_media_status, kit_bool_t *NONNULL out_is_subgrp, planetkit_subgrp_name_t *NONNULL out_tagged_subgrp_name);
kit_bool_t  planetkit_my_media_status_is_audio_muted(planetkit_my_media_status_t *NONNULL my_media_status);

kit_bool_t  planetkit_my_media_status_add_handler(planetkit_my_media_status_t *NONNULL my_media_status, void *NULLABLE user_ptr, planetkit_my_media_status_updated_evt_handler_t NONNULL handler,
                                                  void *NULLABLE result_user, planetkit_result_handler_t NULLABLE result_handler);
kit_bool_t  planetkit_my_media_status_remove_handler(planetkit_my_media_status_t *NONNULL my_media_status, void *NULLABLE user_ptr, planetkit_my_media_status_updated_evt_handler_t NONNULL handler,
                                                     void *NULLABLE result_user, planetkit_result_handler_t NULLABLE result_handler);

#if defined(__cplusplus)
}
#endif

#endif /* __PLANETKIT_MY_STATUS_H__ */
